---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/locked: "true"
    flux.weave.works/locked_msg: '"locked by spencer@weave.works"'
    flux.weave.works/locked_user: spencer <spencer@weave.works>
    flux.weave.works/true: "true"
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1-alpine-perl
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
